### ISSUE TITLE
FR: Ephemeral CommandError handling

### ISSUE THREAD

**Issue by ashleney** [Cursed-Solutions/Tanjun#263]
`CommandError` should preferably give an ephemeral message whenever possible.

**Comment by FasterSpeeding** [comment]
You can already use ephemeral_default to get behaviour like this and it'd be weird for command error to be private in the context of slash commands but public in the context of message commands

**Comment by ashleney** [comment]
Won't `ephemeral_default` affect everything including normal replies? I don't think that's ideal for most use-cases.

There are already a lot of differences between slash and prefix commands anyways.

**Comment by FasterSpeeding** [comment]
> Won't ephemeral_default affect everything including normal replies? I don't think that's ideal for most use-cases.

yeah this is pretty much its intended use case, to set whether stuff that's out of your control like extensions, checks, hooks etc etc make ephemeral responses since these will likely be using .respond which will also be editing in deferred responses and thus can't take flags for that.

Also there's no guarantee people will want CommandErrors to give ephemeral responses since its really just a raised CommandResponse, it can just as easily be used to give intentionally public responses
