### ISSUE TITLE
Allow passing in a function as prefix

### ISSUE THREAD

**Issue by yowoda** [Cursed-Solutions/Tanjun#8]
You should be able to pass in a function that takes the Client and Message as arguments and expect it to return either a string or an Iterable of strings. Great work from what I have seen until now

**Comment by FasterSpeeding** [comment]
Sry for the late response, been a busy week for me but what exactly is the purpose of this function idea (like what would be done with the result of it)? kind of sounds like a arg parser but i'm not sure i'm quite understand this idea.

**Comment by yowoda** [comment]
It can be used to customize prefixes for each guild, e.g. check the database with the guild ID and return the prefix set

**Comment by FasterSpeeding** [comment]
> It can be used to customize prefixes for each guild, e.g. check the database with the guild ID and return the prefix set

In theory you can add custom prefix handling by subclassing the main bot class right now but I'm planning on moving away from any subclassing specific behaviour that's present in the lib sooner or later so i'll add something like this  (although probably gonna consider whether I'll use builder style methods for this rather than putting everything in the init)

**Comment by FasterSpeeding** [comment]
BTW as a follow up, this is being implemented by #29 but likely won't be released until 2.1.0 along with slash command support and some refactors to how resources like commands are loaded into to components and the interface (probably also gonna have dependency injection)

**Comment by FasterSpeeding** [comment]
This is now on #master along with other improvements
